---
title: "awtp.line.level.sims.calc"
author: "knottit"
date: "March 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

need to create a single file that combines awtp.lead.2018 & awtp.lag.2018 and then add the calcoolated columnes for SIMS, etc.

WHAT THE HELL IS awtp.brb.all.cast. that is output from MEXSYS - SIMS 1.1.Rmd



```{r}


library(tidyr)
library(tidyverse)
library(reshape2)
library(plyr)
library(ggplot2)
library(ggthemes)
library(openxlsx)
library(sqldf)
#library(xlsx)
library(taRifx)

# bring in the data files generated by the MEXSYS script... WE SHOULD CHANGE THIS!
# these files should be bound together and dumped onto the ADD directory and used as input into PowerBI (?)

awtp.lead.2018 <- read.csv("Z:/KCSubsite/awtp.lead.2018.csv", stringsAsFactors = FALSE)
awtp.lag.2018  <- read.csv("Z:/KCSubsite/awtp.lag.2018.csv", stringsAsFactors = FALSE)

# remove .'s and _'s from column names
names(awtp.lead.2018) <- gsub("\\.", "", names(awtp.lead.2018))
names(awtp.lag.2018) <- gsub("\\.", "", names(awtp.lag.2018))

process_loc <- read.csv("Z:/PROMAN/Automated Data Downloads/awp.prc.loc.csv", stringsAsFactors = FALSE)

process_loc$location_process <- paste(process_loc$location, process_loc$process, sep = " ")

names(process_loc) <- tolower(names(process_loc))

awtp.lag.sims <-  merge(x = awtp.lag.2018, y = process_loc, by = "mfg_location_line", all.x = TRUE)

awtp.lead.sims <-  merge(x = awtp.lead.2018, y = process_loc, by = "mfg_location_line", all.x = TRUE)

awtp.2018.sims <-  merge(x = awtp.lag.sims, y = awtp.lead.sims, by = c("mfg_location_line", "data", "lcnprclnsims"))

# get rid of the na's... na, na, na, na... hey, hey, hey... goodbye... har.. har.. har...
awtp.2018.sims[is.na(awtp.2018.sims)] <- 0

names(awtp.2018.sims) <- gsub("\\.", "", names(awtp.2018.sims))
names(awtp.2018.sims) <- gsub("\\_", "", names(awtp.2018.sims))


awtp.2018.sims$data <- as.character(awtp.2018.sims$data)

awtp.2018.sims$data[awtp.2018.sims$data == "Feb-18"] <- "2018-02"
awtp.2018.sims$data[awtp.2018.sims$data == "Jan-18"] <- "2018-01"
awtp.2018.sims$data[awtp.2018.sims$data == "Mar-18"] <- "2018-03"
awtp.2018.sims$data[awtp.2018.sims$data == "Apr-18"] <- "2018-04"
awtp.2018.sims$data[awtp.2018.sims$data == "May-18"] <- "2018-05"
awtp.2018.sims$data[awtp.2018.sims$data == "Jun-18"] <- "2018-06"
awtp.2018.sims$data[awtp.2018.sims$data == "Jul-18"] <- "2018-07"
awtp.2018.sims$data[awtp.2018.sims$data == "Aug-18"] <- "2018-08"
awtp.2018.sims$data[awtp.2018.sims$data == "Sep-18"] <- "2018-09"
awtp.2018.sims$data[awtp.2018.sims$data == "Oct-18"] <- "2018-10"
awtp.2018.sims$data[awtp.2018.sims$data == "Nov-18"] <- "2018-11"
awtp.2018.sims$data[awtp.2018.sims$data == "Dec-18"] <- "2018-12"


# normalize the percentage fields

awtp.2018.sims$X5sscore[awtp.2018.sims$X5sscore > 1] <- (awtp.2018.sims$X5sscore[awtp.2018.sims$X5sscore > 1]) / 100 
awtp.2018.sims$dmaudit[awtp.2018.sims$dmaudit > 1] <- (awtp.2018.sims$dmaudit[awtp.2018.sims$dmaudit > 1]) / 100 
awtp.2018.sims$recovery[awtp.2018.sims$recovery >= 1] <- (awtp.2018.sims$recovery[awtp.2018.sims$recovery >= 1]) / 100 
awtp.2018.sims$scrap[awtp.2018.sims$scrap >= 1] <- (awtp.2018.sims$scrap[awtp.2018.sims$scrap >= 1]) / 100 
awtp.2018.sims$net.melt.loss[awtp.2018.sims$net.melt.loss >= 1] <- (awtp.2018.sims$net.melt.loss[awtp.2018.sims$net.melt.loss >= 1]) / 100 


# change name of AWPM Casthoust to MCC
awtp.2018.sims$locationx <- as.character(awtp.2018.sims$locationx) # make it char to get rid of factor levels
awtp.2018.sims$processx <- as.character(awtp.2018.sims$processx) # make it char to get rid of factor levels
awtp.2018.sims$locationx[awtp.2018.sims$locationx == "AWPM" & awtp.2018.sims$processx == "Casting"] <- "MCC"

# ADD SIMS fields here...

# A3 score
awtp.2018.sims$a3.sims.scr.1 <- ifelse(awtp.2018.sims$Xofa3sopened > 0 & awtp.2018.sims$Xofa3sopened < 2, 1,     
                  ifelse(awtp.2018.sims$Xofa3sopened > 1, 2, 0))

awtp.2018.sims$a3.sims.scr.2 <- ifelse(awtp.2018.sims$Xofa3scompleted > 0 & awtp.2018.sims$Xofa3scompleted < 2, 1,     
                  ifelse(awtp.2018.sims$Xofa3scompleted > 1, 2, 0))

awtp.2018.sims$a3.sims.scr.3 <- ifelse(awtp.2018.sims$Xofa3sgt30days > 0 & awtp.2018.sims$Xofa3sgt30days < 2, -1,     
                  ifelse(awtp.2018.sims$Xofa3sgt30days > 1, -2, 0))

awtp.2018.sims$a3.step.uno <- (awtp.2018.sims$a3.sims.scr.1 + awtp.2018.sims$a3.sims.scr.2 + awtp.2018.sims$a3.sims.scr.3)

awtp.2018.sims$a3.step.dos <- (awtp.2018.sims$a3.step.uno / 4)

awtp.2018.sims$a3.step.tres <- ifelse(awtp.2018.sims$a3.step.dos < 0, 0, awtp.2018.sims$a3.step.dos)

awtp.2018.sims$mtbf <- (awtp.2018.sims$totalscheduletime / awtp.2018.sims$repaircount)

awtp.2018.sims$reliability <- (awtp.2018.sims$mtbf / (awtp.2018.sims$mttravgrepairtimeminutes / 60 + awtp.2018.sims$mtbf))

#probably add lower limit if negatvie number a3score = 0
awtp.2018.sims$a3score <- (0.15 * awtp.2018.sims$a3.step.tres)

awtp.2018.sims$`5sscore` <- (0.15 * awtp.2018.sims$X5sscore)

awtp.2018.sims$dmscore <- (0.15 * awtp.2018.sims$dmaudit)

awtp.2018.sims$pmcompliancescore <- (0.25 * (awtp.2018.sims$actualpmworkorders / awtp.2018.sims$plannedpmworkorders))

awtp.2018.sims$reliabilityscore <- (0.3 * awtp.2018.sims$reliability)

awtp.2018.sims$lead.sims.score <- (awtp.2018.sims$a3score + awtp.2018.sims$`5sscore` + awtp.2018.sims$dmscore + awtp.2018.sims$pmcompliancescore + awtp.2018.sims$reliabilityscore)

# Lagging

awtp.2018.sims$lagg.oa.wtd <- 0.3*awtp.2018.sims$oa
awtp.2018.sims$lagg.pe.wtd <- 0.15*awtp.2018.sims$pe
awtp.2018.sims$lagg.qr <- 0.15*awtp.2018.sims$qr


# NEED VARIABLE AND UNIT COST DATA!!!!!!!
#awtp.2018.sims$lagg.var.labor.unit.cost <- 0.2*awtp.2018.sims$var.lbr.unt.cst
awtp.2018.sims$lagg.var.labor.unit.cost <- 0

# Casting Lagging 

#- need to index update for CASTING ONLY? 
# or just change the variable name and only use casting for casting???
awtp.2018.sims$cast.lagg.oa.wtd <- 0.25*awtp.2018.sims$oa
awtp.2018.sims$cast.lagg.scrap.wtd <- 0.15*awtp.2018.sims$scrap #do we need to multiply scrap by 100 before weighting?
awtp.2018.sims$cast.lagg.net.melt.loss.wtd <- 0.10*awtp.2018.sims$netmeltloss
awtp.2018.sims$cast.lagg.rcvry.wtd <- 0.10*awtp.2018.sims$recovery

# HOW TO CALC METRIC TONE PER HOUR?!?!?!?
awtp.2018.sims$cast.lagg.metric.tons.per.hour.wtd <- 0.20*(awtp.2018.sims$goodoutput/awtp.2018.sims$mixadjustedcycletime) # THIS IS WRONG!!!!
awtp.2018.sims$cast.lagg.labor.metric.tons.per.hour.wtd <- 0.10*awtp.2018.sims$laborhourspermetricton
awtp.2018.sims$cast.lagg.labor.metric.tons.per.hour.wtd <- 0.10*awtp.2018.sims$energypermetricton


#Select min from MACT to do the one calculation thingy that you need min for...by lcnprclnsims
MACT.temp.mins <- sqldf("SELECT locationprocessx, min(mixadjustedcycletime) from [awtp.2018.sims] where mixadjustedcycletime>0 group by locationprocessx")

#Make MACT calculation and weight it
awtp.2018.sims <- merge(awtp.2018.sims, MACT.temp.mins)
awtp.2018.sims$lagg.mact <- awtp.2018.sims$`min(mixadjustedcycletime)`/awtp.2018.sims$mixadjustedcycletime
awtp.2018.sims$lagg.mact.wtd <- 0.2*awtp.2018.sims$lagg.mact



tbl_lag_line <- sqldf("SELECT [locationx] as Mfg_Location
                      ,'Actual' as Plan_Type
                      ,'2018' as line_year
                      ,[data] as report_month
                      ,[processx] as process_type
                      ,[goodoutput] as prod_units
                      ,[goodoutput] as good_prod_units
                      ,[scrap] as scrap_units
                      ,[scrap] as scrap_units_src
                      ,[rework] as rework_units
                      ,[rework] as rework_units_src
                      ,[scheduledproductiontime] as total_time
                      ,[runtime] as run_time
                      ,[effectiveruntime] as eff_run_time
                      ,[fullyproductivehours] as full_prod_hrs
                      ,[totalcalendartime] as calendar_time
                      , 1 as process_lines
                      , 1 as process_lines_avg
                      ,[mixadjustedcycletime] as M_A_Cycle_Time_avg
                      ,[scrap] as scrap_pct_avg
                      ,[rework] as rework_pct_avg
                      ,[qr] as quality_rate_avg
                      ,[oa] as oa_avg
                      ,[pe] as perf_rate_avg
                      ,[oee] as oee_avg
                      ,[au] as asset_utilization_avg
                      ,[au] as asset_utilization_weight
                      ,[lcnprclnsims] as location_line_sims
                      ,[reportgroupx] as report_group
                      from    [awtp.2018.sims]
                      where [data] in ('2018 YTD', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12')")


tbl_lead_line <- sqldf("SELECT [locationx] as Mfg_Location
                       ,'Actual' as Plan_Type
                       ,'2018' as line_year
                       ,[data] as report_month
                       ,[processx] as process_type
                       ,[Xofrecognitions] as people_recognized
                       ,[Xofsuggestions] as suggestions_submitted
                       ,[Xofa3sopened] as prob_a3_opened
                       ,[Xofa3scompleted] as prob_a3_completed
                       ,[Xofa3sgt30days] as prob_a3_over_30
                       ,0 as 'events'
                       ,[X5sscore] as five_s_audit
                       ,0 as critical_equip
                       ,0 as crit_equip_in_tpm
                       ,0 as proc_mgmt_review
                       ,0 as recipe_audits
                       ,0 as recipe_misses
                       ,[dmaudit] as dm_audit_score
                       ,0 as expected_pm_time
                       ,0 as total_pm_time
                       ,[plannedpmworkorders] as expected_pm_orders
                       ,[actualpmworkorders] as total_pm_orders
                       ,[repaircount] as repair_count
                       ,[mttravgrepairtimeminutes] as mttr_avg_time
                       ,[lcnprclnsims] as location_line_sims
                       ,[reportgroupx] as report_group
                       from    [awtp.2018.sims]
                       where [data] in ('2018 YTD', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12')")




tbl_cast_line <- sqldf("select [locationx] as Mfg_Location
                       ,'Actual' as Plan_Type
                       ,'2018' as line_year
                       ,[data] as report_month
                       ,[processx] as process_type
                       ,[goodoutput]	as	prod_weight
                       ,0	as	planned_scrap_weight
                       ,0	as	unplanned_scrap_weight
                       ,0	as	charge_weight_solid
                       ,0	as	charge_weight_rsi
                       ,0	as	charge_weight_chip
                       ,0	as	dross_weight
                       ,0	as	good_weight_shipped
                       ,0	as	dross_after_recovery
                       ,[lightsontime]	as	total_time
                       ,[runtime]	as	run_time
                       ,[effectiveruntime]	as	eff_run_time
                       ,[fullyproductivehours]	as	full_prod_hours
                       ,[totalcalendartime]	as	calendar_time
                       ,[processlinex]	as	process_lines
                       ,0	as	Direct_LH_Unit
                       ,0	as	total_charge_wt
                       ,0	as	gas_gj
                       ,0	as	electricity_gj
                       ,[qr]	as	quality_rate_avg
                       ,[oa]	as	oa_avg
                       ,[pe]	as	perf_rate_avg
                       ,[oee]	as	oee_avg
                       ,[au]	as	asset_utilization_avg
                       ,[au]	as	asset_utilization_weight
                       ,[scrap]	as	scrap_pct_avg
                       ,[recovery]	as	recovery_pct_avg
                       ,[laborhourspermetricton]	as	lh_mt_avg
                       ,[energypermetricton]	as	gj_mt_avg
                       ,[netmeltloss]	as	net_melt_loss_avg
                       ,[lcnprclnsims] as location_line_sims
                       ,[reportgroupx] as report_group
                       from    [awtp.2018.sims]
                       where [processx] in ('Casting')
                       and [data] in ('2018 YTD', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12')")


#change names to lower case
names(tbl_lag_line) <- tolower(names(tbl_lag_line))
names(tbl_lead_line) <- tolower(names(tbl_lead_line))
names(tbl_cast_line) <- tolower(names(tbl_cast_line))

# read in the history to append to curent year
awp.sims.lagg.hist <- read.csv("Z:/PROMAN/Automated Data Downloads/awp.sims.lagg.hist.csv")
names(awp.sims.lagg.hist) <- tolower(names(awp.sims.lagg.hist))
awp.sims.lagg.hist$location_line_sims <- paste(awp.sims.lagg.hist$mfg_location, awp.sims.lagg.hist$process_type, sep = " - ")
awp.sims.lagg.hist$report_group <- "process"


awp.sims.lead.hist <- read.csv("Z:/PROMAN/Automated Data Downloads/awp.sims.lead.hist.csv")
names(awp.sims.lead.hist) <- tolower(names(awp.sims.lead.hist))
awp.sims.lead.hist$location_line_sims <- paste(awp.sims.lead.hist$mfg_location, awp.sims.lead.hist$process_type, sep = " - ")
awp.sims.lead.hist$report_group <- "process"

awp.sims.cast.hist <- read.csv("Z:/PROMAN/Automated Data Downloads/awp.sims.cast.hist.csv")
names(awp.sims.cast.hist) <- tolower(names(awp.sims.cast.hist))
awp.sims.cast.hist$location_line_sims <- paste(awp.sims.cast.hist$mfg_location, awp.sims.cast.hist$process_type, sep = " - ")
awp.sims.cast.hist$report_group <- "process"


# combine the data frames to output to Automated Data Downloads
tbl_cast_all <- rbind(awp.sims.cast.hist, tbl_cast_line)
tbl_lag_all <- rbind(awp.sims.lagg.hist, tbl_lag_line)
tbl_lead_all <- rbind(awp.sims.lead.hist, tbl_lead_line)

## CHANGE FILE LOCATIONS TO WEB ADDRESS NOT MAPPED NETWORK LOCATIONS!!!

write.csv(tbl_lag_all, "Z:/KCSubsite/awtp.lagg.line.csv", row.names = FALSE)
write.csv(tbl_lead_all, "Z:/KCSubsite/awtp.lead.line.csv", row.names = FALSE)
write.csv(tbl_cast_all, "Z:/KCSubsite/awtp.cast.line.csv", row.names = FALSE)


#write.csv(awtp.2018.sims, "Z:/KCSubsite/awtp.2018.sims.line.level.calcs.csv")

# read in unit cost data and add/merge stuffs
awtp.unit.cost.labor <- read.csv(file = "Z:/KCSubsite/awtp.2018.unit.cost.labor.melt.csv")
awtp.unit.cost.variable <- read.csv(file = "Z:/KCSubsite/awtp.2018.unit.cost.variable.cost.melt.csv")

#rename column or the files won't merge
names(awtp.unit.cost.labor)[5] <- "data"
names(awtp.unit.cost.labor)[3] <- "costlocation"
#names(awtp.unit.cost.labor)[2] <- "loc"
names(awtp.unit.cost.labor)[6] <- "laborunitcost"

awtp.2018.sims$locationprocessx[awtp.2018.sims$locationprocessx == "AWPE FInishing"] <- "AWPE Finishing"
awtp.2018.sims$locationprocessy[awtp.2018.sims$locationprocessy == "AWPE FInishing"] <- "AWPE Finishing"
awtp.2018.sims$processx[awtp.2018.sims$processx == "FInishing"] <- "Finishing"
awtp.2018.sims$processy[awtp.2018.sims$processy == "FInishing"] <- "Finishing"
awtp.2018.sims$processprocesslinex[awtp.2018.sims$processprocesslinex == "FInishing - DB2 Polish"] <- "Finishing - DB2 Polish"
awtp.2018.sims$processprocessliney[awtp.2018.sims$processprocessliney == "FInishing - DB2 Polish"] <- "Finishing - DB2 Polish"
awtp.2018.sims$lcnprclnsims[awtp.2018.sims$lcnprclnsims == "AWPE - FInishing - DB2 Polish"] <- "AWPE - Finishing - DB2 Polish"

cost.loc <- merge(awtp.unit.cost.labor, process_loc, by = "costlocation", all = FALSE)
cost.loc <- subset(cost.loc, select = c(costlocation, data, laborunitcost, lcnprclnsims))
awtp.sims.unit.cost.loc <- merge(cost.loc, awtp.2018.sims, by = c("lcnprclnsims", "data"))

#rename column or the files won't merge
names(awtp.unit.cost.variable)[5] <- "data"
names(awtp.unit.cost.variable)[3] <- "costlocation"
#names(awtp.unit.cost.variable)[2] <- "loc"
names(awtp.unit.cost.variable)[6] <- "variableunitcost"


var.cost.loc <- merge(awtp.unit.cost.variable, process_loc, by = "costlocation", all = FALSE)
var.cost.loc <- subset(var.cost.loc, select = c(costlocation, data, variableunitcost, lcnprclnsims))
awtp.sims.var.cost.loc <- merge(var.cost.loc, awtp.2018.sims, by = c("lcnprclnsims", "data"))




```

