---
title: "MEXSYS"
author: "The Bard"
date: "January 25, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(officer)
library(tidyr)
library(tidyverse)
library(reshape2)
library(plyr)
library(sqldf)



```

Input:
Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx

Output:
Z:/KCSubsite/awtp.2018.unit.cost.labor.melt.csv
Z:/KCSubsite/awtp.2018.unit.cost.variable.cost.melt.csv

```{r}
library(openxlsx)

awtp.unit.cost.1 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 5, startRow = 2, colNames = FALSE) 
awtp.unit.cost.1$Mfg_location_line <- "Forging" 

awtp.unit.cost.2 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 6, startRow = 2, colNames = FALSE) 
awtp.unit.cost.2$Mfg_location_line <- "Machining" 

awtp.unit.cost.3 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 7, startRow = 2, colNames = FALSE)
awtp.unit.cost.3$Mfg_location_line <- "Satin" 

awtp.unit.cost.4 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 8, startRow = 2, colNames = FALSE) 
awtp.unit.cost.4$Mfg_location_line <- "Polish" 

awtp.unit.cost.5 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 9, startRow = 2, colNames = FALSE) 
awtp.unit.cost.5$Mfg_location_line <- "Dura-bright" 

awtp.unit.cost.6 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 10, startRow = 2, colNames = FALSE)
awtp.unit.cost.6$Mfg_location_line <- "Pack & Ship" 

awtp.unit.cost.7 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 11, startRow = 2, colNames = FALSE) 
awtp.unit.cost.7$Mfg_location_line <- "Megaline" 

awtp.unit.cost.8 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 12, startRow = 2, colNames = FALSE) 
awtp.unit.cost.8$Mfg_location_line <- "Admin" 

awtp.unit.cost.9 <-  readWorkbook("Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx", sheet = 13, startRow = 2, colNames = FALSE) 
awtp.unit.cost.9$Mfg_location_line <- "Casting" 

#combine all cle into dataframe
awtp.unit.cost <- rbind(awtp.unit.cost.1, awtp.unit.cost.2, awtp.unit.cost.3, awtp.unit.cost.4, awtp.unit.cost.5, awtp.unit.cost.6, awtp.unit.cost.7, awtp.unit.cost.8)

#Clear the workspace objects no longer needed
rm(awtp.unit.cost.1, awtp.unit.cost.2, awtp.unit.cost.3, awtp.unit.cost.4, awtp.unit.cost.5, awtp.unit.cost.6, awtp.unit.cost.7, awtp.unit.cost.8, awtp.unit.cost.9)

#add the location onto each row (btw...this was a pain in the tuckus to figure out!)

awtp.unit.cost$loc <- rep("NA", nrow(awtp.unit.cost))

awtp.unit.cost[1, 160] <-  awtp.unit.cost[1,1] # MAKE SURE NUMBER OF COLUMNS DOESNT CHANGE OR CHANGE CODE TO ONLY PULL 2018 cols???

# first update the rows that we know something about... Unit cost starts the dataset for each location, so update those based on X1

  for (n in 2:nrow(awtp.unit.cost)){
    awtp.unit.cost[n, 160] <- ifelse(awtp.unit.cost[n,1] == "Unit costs", awtp.unit.cost[n-1,1], awtp.unit.cost[n,160])
  }
# use the row above if the current row is still "NA" (initialized earlier. not NA but "NA")
  for (n in 2:nrow(awtp.unit.cost)){
    awtp.unit.cost[n,160] <- ifelse(awtp.unit.cost[n,160] == "NA", awtp.unit.cost[n-1,160], awtp.unit.cost[n,160])
  }
    
# add combine process and location for joining to other files

awtp.unit.cost$mfg_process <- awtp.unit.cost$Mfg_location_line

awtp.unit.cost$Mfg_location_line <- paste(awtp.unit.cost$loc, awtp.unit.cost$mfg_process, sep = " ")

awtp.unit.cost <- awtp.unit.cost[,c(160, 159 ,1 , 132, 145:158)]

#"Z:/PROMAN/Automated Data Downloads/Unit Cost Dump File.xlsx"(awtp.unit.cost)

wtf1 <- sqldf("select * from [awtp.unit.cost] where X1 in ('Labor', 'Variable cost')")

wtf1[is.na(as.matrix(wtf1))] <- 0

#subset into two files, one for Labor, one for Variable.  After separate, melt it, change column anmes and then merge to get costs on correct month/year


names(wtf1)[4] <- "2016 Year"
names(wtf1)[5] <- "2017 Year"
names(wtf1)[6] <- "2018-01"
names(wtf1)[7] <- "2018-02"
names(wtf1)[8] <- "2018-03"
names(wtf1)[9] <- "2018-04"
names(wtf1)[10] <- "2018-05"
names(wtf1)[11] <- "2018-06"
names(wtf1)[12] <- "2018-07"
names(wtf1)[13] <- "2018-08"
names(wtf1)[14] <- "2018-09"
names(wtf1)[15] <- "2018-10"
names(wtf1)[16] <- "2018-11"
names(wtf1)[17] <- "2018-12"
names(wtf1)[18] <- "2018 YTD"


awtp.2018.unit.cost.labor <- subset(wtf1, wtf1$X1 == 'Labor')
awtp.2018.unit.cost.variable.cost <- subset(wtf1, wtf1$X1 == 'Variable cost')

awtp.2018.unit.cost.labor.melt <- melt(awtp.2018.unit.cost.labor, id.vars = c("loc", "Mfg_location_line", "X1"))
awtp.2018.unit.cost.variable.cost.melt <- melt(awtp.2018.unit.cost.variable.cost, id.vars = c("loc", "Mfg_location_line", "X1"))


write.csv(awtp.2018.unit.cost.labor.melt, file = "Z:/KCSubsite/awtp.2018.unit.cost.labor.melt.csv")
write.csv(awtp.2018.unit.cost.variable.cost.melt, file = "Z:/KCSubsite/awtp.2018.unit.cost.variable.cost.melt.csv")

```